CommitteeSCAddress = "0xECc22f3EcD0EFC8aD77A78ad9469eFbc44E746F5"
LagrangeServiceSCAddress = "0x35F4f28A8d3Ff20EEd10e087e8F96Ea2641E6AA2"
EthereumRPCURL = "--- Ethereum RPC URL (holesky or mainnet) ---"
BLSCurve = "BN254"
DockerImageTag = "v0.3.7"
ConcurrentFetchers = 8
