OperatorKeystorePath = "--- Operator Keystore Path ---"
OperatorKeystorePassword = "--- Operator Keystore Password (can be empty if password path is provided) ---"
OperatorKeystorePasswordPath = "--- Operator Keystore Password Path ---"
SignerECDSAKeystorePath = "--- Signer ECDSA Keystore Path ---"
SignerECDSAKeystorePassword = "--- Signer ECDSA Keystore Password (can be empty if password path is provided) ---"
SignerECDSAKeystorePasswordPath = "--- Signer ECDSA Keystore Password Path ---"
BLSKeystorePath = "--- BLS Keystore Path ---"
BLSKeystorePassword = "--- BLS Keystore Password (can be empty if password path is provided) ---"
BLSKeystorePasswordPath = "--- BLS Keystore Password Path ---"
EthereumRPCURL = "--- Ethereum RPC URL (mainnet / holesky) ---"
L1RPCEndpoint = "--- L1 RPC Endpoint (mainnet) ---"
BeaconURL = "--- Beacon Endpoint (mainnet) ---"
BLSCurve = "BN254"
ConcurrentFetchers = 8