OperatorPrivateKey = "--- Operator ECDSA Private Key ---"
OperatorKeystorePath = "--- Operator Keystore Path (empty if private key is provided) ---"
OperatorKeystorePassword = "--- Operator Keystore Password (should be provided if keystore path is provided) ---"
SignerPrivateKey = "--- Signer ECDSA Private Key ---"
SignerKeystorePath = "--- Signer Keystore Path (empty if private key is provided) ---"
SignerKeystorePassword = "--- Signer Keystore Password (should be provided if keystore path is provided) ---"
BLSPrivateKey = "--- BLS Private Key ---"
BLSKeystorePath = "--- BLS Keystore Path (empty if private key is provided) ---"
BLSKeystorePassword = "--- BLS Keystore Password (should be provided if keystore path is provided) ---"
EthereumRPCURL = "--- Ethereum RPC URL (mainnet / holesky) ---"
L1RPCEndpoint = "--- L1 RPC Endpoint (mainnet) ---"
BeaconURL = "--- Beacon Endpoint (mainnet) ---"
BLSCurve = "BN254"
ConcurrentFetchers = 8