version: "3.7"

services:
  lagrange_attestation_node: # Modify if you want to change the service name
    container_name: lagrange_attestation_node # Modify if you want to change the container name
    image: lagrangelabs/lagrange-node:v0.4.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPATH=/app/config/keystore/bls.key
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPASSWORDPATH=/app/config/keystore/bls.pass
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPATH=/app/config/keystore/signer.key
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPASSWORDPATH=/app/config/keystore/signer.pass
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-client -c /app/config/client.toml"
    volumes:
      - <Client config absolute path>:/app/config/client.toml # Modify
      - <BLS key absolute path>:/app/config/keystore/bls.key # Modify
      - <BLS key password file absolute path>:/app/config/keystore/bls.pass # Modify
      - <ECDSA Signer key absolute path>:/app/config/keystore/signer.key # Modify
      - <ECDSA Signer key password file absolute path>:/app/config/keystore/signer.pass # Modify
      - <Named Volume name>:$HOME/.lagrange # Modify mounted volume name - should be the same as the named volume
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  named_volume_name: # Modify
