[Client]
GrpcURLs = "--- GrpcUrl of Chain ---"
Chain = "--- Chain name ---"
EthereumURL = "--- Ethereum RPC Endpoint of network (holesky/mainnet) ---"
OperatorAddress = "--- EigenLayer Operator Address ---"
CommitteeSCAddress = "0x57BAf26C77BBBa3D3A8Bd620c8d74B44Bfda8818"
BLSKeystorePath = "--- BLS Keystore Path ---"
BLSKeystorePasswordPath = "--- BLS Keystore Password Path ---"
SignerECDSAKeystorePath = "--- Signer ECDSA Keystore Path ---"
SignerECDSAKeystorePasswordPath = "--- Signer ECDSA Keystore Password Path ---"
PullInterval = "1000ms"
BLSCurve = "BN254"

[RpcClient]
        
        [RpcClient.<Chain Name>]
        RPCURL = "--- Rollup chain's mainnet RPC endpoint ---"
        L1RPCURL = "--- Ethereum mainnet RPC endpoint ---"
        BeaconURL = "--- Beacon mainnet RPC endpoint ---"
        BatchInbox = "--- Batch Inbox Contract Address ---"
        ConcurrentFetchers = "8"
        
[Telemetry]
        ServiceName = "lagrange-node"
        PrometheusRetentionTime = "60s"